import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute, setCatchHandler } from 'workbox-routing';
import { NetworkFirst, CacheFirst } from 'workbox-strategies';

//precache assets generated by Vite/Workbox
precacheAndRoute(self.__WB_MANIFEST);

//cache static assets
registerRoute(
    ({ request }) =>
        request.destination === 'script' ||
        request.destination === 'style' ||
        request.destination === 'image',
    new CacheFirst({ cacheName: 'assets' }),    //cache first
);

//page navigations: network first
registerRoute(
    ({ request }) => request.mode === 'navigate',
    new NetworkFirst({
        cacheName: 'pages',
        networkTimeoutSeconds: 3,   //cache if network timeout
    }),
);

self.addEventListener('install', (event) => {
    event.waitUntil(
        //offline fallback for navigations
        (async () => {
            const cache = await caches.open('offline');
            await cache.add('/offline.html');
        })(),
    );
    self.skipWaiting();
});

self.addEventListener('activate', (event) => {
    //ensures sw controls the page without a reload
    event.waitUntil(self.clients.claim());
});

//fallback to offline.html if navigation fails
setCatchHandler(async ({ event }) => {
    if (event.request.mode === 'navigate') {
        const cache = await caches.open('offline');
        const cached = await cache.match('/offline.html');
        return cached || Response.error();
    }
    return Response.error();
});

//push notification handler
self.addEventListener('push', (event) => {
    const data = (event.data && event.data.json && event.data.json()) || {};
    const title = data.title || 'Expense Tracker';
    const body = data.body || 'Notification';
    const url = data.url || '/app/dashboard';

    event.waitUntil(
        self.registration.showNotification(title, {
            body,
            data: { url },
        }),
    );
});

//notification click, open/focus app
self.addEventListener('notificationclick', (event) => {
    console.log('notificationclick', event.notification.data);
    event.notification.close();
    const url = (event.notification.data && event.notification.data.url) || '/';

    event.waitUntil(
        (async () => {
            //get all window clients
            const allClients = await clients.matchAll({ 
                type: 'window', 
                includeUncontrolled: true,
            });

            for (const client of allClients) {
                if('focus' in client) {
                    await client.focus();
                    //navigate existing tab to the target URL
                    if('navigate' in client) {
                        return client.navigate(url);
                    }
                    return;
                }
            }

            //else open new window/tab
            return self.clients.openWindow(url);
        })(),
    );
});